import { useState } from "react";
const DATA = [
  { id: 1, name: "Admin User", email: "admin@lumiere.com", role: "Super Admin", status: "Active" },
  { id: 2, name: "Floor Manager", email: "manager@lumiere.com", role: "Manager", status: "Active" },
];
const EMPTY = { name: "", email: "", role: "Staff", status: "Active" };
export default function AdminUsers() {
  const [rows, setRows] = useState(DATA); const [modal, setModal] = useState(null); const [form, setForm] = useState(EMPTY);
  const close = () => setModal(null);
  const save = () => { if (!form.name.trim() || !form.email.trim()) return; if (modal.mode === "add") setRows((p) => [...p, { id: Date.now(), ...form }]); if (modal.mode === "edit") setRows((p) => p.map((r) => r.id === modal.row.id ? { ...r, ...form } : r)); close(); };
  return <div className="ad_page"><div className="rooms__header"><div><h2 className="ad_h2">Admin User Management</h2><p className="ad_p">Manage admin accounts, roles and permissions.</p></div><button className="rooms__add_btn" onClick={() => { setForm(EMPTY); setModal({ mode: "add" }); }}>Add Admin</button></div><div className="ad_table_wrap"><table className="ad_table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td>{r.name}</td><td>{r.email}</td><td>{r.role}</td><td><span className="ad_chip">{r.status}</span></td><td className="rooms__actions_cell"><button className="rooms__icon_btn" onClick={() => { setForm(r); setModal({ mode: "edit", row: r }); }}>Edit</button><button className="rooms__icon_btn rooms__icon_btn--danger" onClick={() => setRows((p) => p.filter((x) => x.id !== r.id))}>Delete</button></td></tr>)}</tbody></table></div>{(modal?.mode==="add"||modal?.mode==="edit")&&<><div className="rooms__modal_overlay" onClick={close}/><div className="rooms__modal_box"><div className="rooms__modal_head"><span className="rooms__modal_title">{modal.mode==="add"?"Add Admin":"Edit Admin"}</span><button className="rooms__modal_close" onClick={close}>x</button></div><div className="rooms__form_row"><label className="rooms__form_label">Name</label><input required className="rooms__form_input" value={form.name} onChange={(e)=>setForm((f)=>({...f,name:e.target.value}))}/></div><div className="rooms__form_row"><label className="rooms__form_label">Email</label><input required type="email" className="rooms__form_input" value={form.email} onChange={(e)=>setForm((f)=>({...f,email:e.target.value}))}/></div><div className="rooms__form_grid2"><div><label className="rooms__form_label">Role</label><select className="rooms__form_select" value={form.role} onChange={(e)=>setForm((f)=>({...f,role:e.target.value}))}><option>Super Admin</option><option>Manager</option><option>Staff</option></select></div><div><label className="rooms__form_label">Status</label><select className="rooms__form_select" value={form.status} onChange={(e)=>setForm((f)=>({...f,status:e.target.value}))}><option>Active</option><option>Inactive</option></select></div></div><div className="rooms__form_actions"><button className="rooms__btn rooms__btn--ghost" onClick={close}>Cancel</button><button className="rooms__btn rooms__btn--primary" onClick={save}>Save</button></div></div></>}</div>;
}
