import { useState } from "react";
import DeleteIconButton from "../components/DeleteIconButton";
const DATA = [
  { id: 1, title: "Weekend Dinner 20% Off", type: "Restaurant", validFrom: "2026-04-01", validTo: "2026-04-30", status: "Active" },
];
const EMPTY = { title: "", type: "Restaurant", validFrom: "", validTo: "", status: "Active" };
const IcEdit = () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M12 20h9" /><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4Z" /></svg>;
export default function AdminOffers() {
  const [rows, setRows] = useState(DATA); const [modal, setModal] = useState(null); const [form, setForm] = useState(EMPTY);
  const close = () => setModal(null); const openAdd = () => { setForm(EMPTY); setModal({ mode: "add" }); };
  const openEdit = (row) => { setForm(row); setModal({ mode: "edit", row }); }; const openDelete = (row) => setModal({ mode: "delete", row });
  const save = () => { if (!form.title.trim() || !form.validFrom || !form.validTo) return; if (modal.mode === "add") setRows((p) => [...p, { id: Date.now(), ...form }]); if (modal.mode === "edit") setRows((p) => p.map((r) => r.id === modal.row.id ? { ...r, ...form } : r)); close(); };
  const remove = () => { setRows((p) => p.filter((r) => r.id !== modal.row.id)); close(); };
  return <div className="ad_page"><div className="rooms__header"><div><h2 className="ad_h2">Offers & Promotions</h2><p className="ad_p">Create promotional campaigns and banners.</p></div><button className="rooms__add_btn" onClick={openAdd}>Add Offer</button></div><div className="ad_table_wrap"><table className="ad_table"><thead><tr><th>Offer</th><th>Type</th><th>From</th><th>To</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td>{r.title}</td><td>{r.type}</td><td>{r.validFrom}</td><td>{r.validTo}</td><td><span className="ad_chip">{r.status}</span></td><td>
    <div className="d-flex" style={{ gap: "6px" }}>
      <button className="rooms__icon_btn" onClick={() => openEdit(r)}><IcEdit /></button>
      <DeleteIconButton onClick={() => openDelete(r)} />
    </div></td></tr>)}</tbody></table></div>{(modal?.mode === "add" || modal?.mode === "edit") && <><div className="rooms__modal_overlay" onClick={close} /><div className="rooms__modal_box"><div className="rooms__modal_head"><span className="rooms__modal_title">{modal.mode === "add" ? "Add Offer" : "Edit Offer"}</span><button className="rooms__modal_close" onClick={close}>x</button></div><div className="rooms__form_row"><label className="rooms__form_label">Title</label><input required className="rooms__form_input" value={form.title} onChange={(e) => setForm((f) => ({ ...f, title: e.target.value }))} /></div><div className="rooms__form_grid2"><div><label className="rooms__form_label">Type</label><select className="rooms__form_select" value={form.type} onChange={(e) => setForm((f) => ({ ...f, type: e.target.value }))}><option>Cafe</option><option>Restaurant</option><option>Bar</option><option>Room</option></select></div><div><label className="rooms__form_label">Status</label><select className="rooms__form_select" value={form.status} onChange={(e) => setForm((f) => ({ ...f, status: e.target.value }))}><option>Active</option><option>Inactive</option></select></div></div><div className="rooms__form_grid2"><div><label className="rooms__form_label">Valid From</label><input required type="date" className="rooms__form_input" value={form.validFrom} onChange={(e) => setForm((f) => ({ ...f, validFrom: e.target.value }))} /></div><div><label className="rooms__form_label">Valid To</label><input required type="date" className="rooms__form_input" value={form.validTo} onChange={(e) => setForm((f) => ({ ...f, validTo: e.target.value }))} /></div></div><div className="rooms__form_actions"><button className="rooms__btn rooms__btn--ghost" onClick={close}>Cancel</button><button className="rooms__btn rooms__btn--primary" onClick={save}>Save</button></div></div></>}{modal?.mode === "delete" && <><div className="rooms__modal_overlay" onClick={close} /><div className="rooms__modal_box"><div className="rooms__modal_head"><span className="rooms__modal_title">Delete Offer</span><button className="rooms__modal_close" onClick={close}>x</button></div><p className="rooms__delete_msg">Delete "{modal.row.title}" offer?</p><div className="rooms__form_actions"><button className="rooms__btn rooms__btn--ghost" onClick={close}>Cancel</button><button className="rooms__btn rooms__btn--danger" onClick={remove}>Delete</button></div></div></>}</div>;
}
